# Generated by Django 4.2.1 on 2023-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_type',
            field=models.CharField(choices=[('Simple', 'Simple'), ('End', 'End'), ('Personal', 'Personal')], max_length=100, verbose_name='Тип рассылки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Оценка'),
        ),
    ]
