# Generated by Django 4.2.1 on 2023-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_mailing_mailing_type_alter_question_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Оценка'),
        ),
    ]
