# Generated by Django 4.2.1 on 2023-06-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_type',
            field=models.CharField(choices=[('Start', 'Start'), ('Simple', 'Simple'), ('End', 'End'), ('Personal', 'Personal')], max_length=100, verbose_name='Тип рассылки'),
        ),
    ]
