# Generated by Django 4.2.1 on 2023-06-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_mailing_mailing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Оценка'),
        ),
    ]
