# Generated by Django 4.2.1 on 2023-06-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='ID пользователя')),
                ('chat_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя')),
                ('first_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Фамилия')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
    ]
